application:
  clickhouse:
    url: jdbc:clickhouse://127.0.0.1:8123/jh_panorama
    driver-class-name: ru.yandex.clickhouse.ClickHouseDriver
    username: default
    password:
  input-directory: D:\WorkSpace\clickhouse-sync\src\test\jh_panorama
  metadata-dir: D:\WorkSpace\clickhouse-sync\src\test\meta
  delimiter: "~@~"
  schema: "default.cmcc_test"
spring:
  batch:
    job:
      enabled: false
