application:
  clickhouse:
    url: jdbc:clickhouse://127.0.0.1:8123/default
    driver-class-name: ru.yandex.clickhouse.ClickHouseDriver
    username: default
    password:
  input-directory: D:\WorkData\WorkSpace\clickhouse-sync\src\test\input\
  metadata-dir: D:\WorkData\WorkSpace\clickhouse-sync\src\test\meta
  delimiter: ","
  schema: "default.cmcc_test"
spring:
  batch:
    job:
      enabled: true
