application:
  clickhouse:
    url: jdbc:clickhouse://127.0.0.1:8123/jh_panorama
    driver-class-name: ru.yandex.clickhouse.ClickHouseDriver
    username: default
    password:
  input-directory: D:\WorkSpace\clickhouse-sync\src\test\simple
  metadata-dir: D:\WorkSpace\clickhouse-sync\src\test\meta
  delimiter: ","
  input-schema: "jh_panorama.panorama"
  file-encoding: UTF-8
spring:
  batch:
    job:
      enabled: false
